### PR TITLE
MVP wfrp support

### PR DESCRIPTION
**Pull request by PiotrZakrzewski**
Hi!

I implemented very basic support support for WFRP 4ed.
There is plenty more that can be implemented (esp trappings, armor, fate/fortune, psychology, races) but this is a first step, to try out how adding it works out and what others think.

PS: I have never worked with VUE, so there might be here more duplication than necessary (skills / stats esp).
cheers!

### CODE REVIEW

**Comment by lordnull** [comment]
Looks good to me. It’ll get a second review later before being merged.

**Comment by PiotrZakrzewski** [comment]
Great! I will add some more functionality to the WFRP support later on (in the coming two weeks I am quite busy).
What changes are you thinking about w.r.t rolls?

**Comment by Morgul** [comment]
Most of the other systems have the ability to click on a skill and it will fill out the dice roller at the top and scroll you to it, letting you modify the roll, and then roll it. The dice rollers often keep a history (in games where that's important). So, something along those lines. (Since I don't know the system whatever makes the most sense.)

**Comment by Morgul** [comment]
This is now live on https://beta.rpgkeeper.com.

**Pull request merged**
